#!/bin/bash
source /etc/profile.d/rvm.sh
TOP_DIR="$(dirname "$BASH_SOURCE")/.."
cd "$TOP_DIR"
bundle exec rails runner 'PostRedirect.delete_old_post_redirects'
bundle exec rails runner 'TrackThingsSentEmail.delete_old_track_things_sent_email'
